### ISSUE TITLE
Allow variables to be updated/renamed via `lagoon update`

### ISSUE THREAD

**Issue by klonos** [uselagoon/lagoon-cli#107]
As it is currently, `lagoon update` does not support `variable` as a command. Here's the what I had to write, to internally document the tasks of updating/renaming variables:

> ## Updating the value of existing variables
> 
> There is currently no single lagoon command to directly in-place update an existing variable (follow this issue for when/if this gets implemented, and update this documentation accordingly: ).
> 
> Instead of updating an existing variable, you will need to do the following:
> 
> - List the variables, using the --reveal flag, so that you see their values.
> - **Make a note of the value of the variable you need to update**
> - **Make a note of the scope of the variable you need to update**
> - Delete the existing variable (**again: make sure you have safely taken note of its value and scope before deleting it!**)
> - Create a new variable, with the same name as the one you deleted in the previous step, and the value and scope you have safely saved from the steps before that.
> 
> **Note**: Since you are essentially creating a new, replacement variable (instead of updating the existing one), the new variable will have a different ID from the one the old variable had (which may or may not matter).
> 
> ## Renaming existing variables
> 
> Same as with updating existing variables, there is no way to directly rename an existing one. What you'll need to do instead is:
> 
> - List the variables, using the --reveal flag, so that you see their values.
> - Create a variable with the new name, with its value and scope set to the same value/scope as the variable you want to rename.
> - List the variables using the --reveal flag once again, to double-check that the new variable has the same value and scope as the one that needs to be renamed.
> - Delete the old variable.

That's too much work 😅 ...can I pleeez haz `lagoon update variable`?

**Comment by shreddedbacon** [comment]
@klonos Lagoon doesn't support updating variables in the API at the moment, there is an issue open to support this though https://github.com/amazeeio/lagoon/issues/1677

In the mean time, we may be able to do `lagoon update variable` that does the deletion, then addition of a variable instead. 

Once lagoon supports updating, we can migrate the command to the proper lagoon supported way.

**Comment by seanhamlin** [comment]
+1 for having the update process just do a delete and an add in the background. For bonus points if you are just changing the value, then the scope should remain the same.

**Comment by seanhamlin** [comment]
Now that https://github.com/uselagoon/lagoon/pull/3204 has landed, the API bits are in place, so I think the CLI just needs to use them.
