### ISSUE TITLE
Deleting a project should delete all environments first

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-cli#117]
**Is your feature request related to a problem? Please describe.**

At the moment, in order to fully delete a project, you are expected to delete the environments first. This is not always respected, and can lead to orphan environments in Lagoon.

**Describe the solution you'd like**

When you delete a project, the confirmation screen should list every (non-deleted) environment, and the confirmation text should read something like:

> You are about to delete the project 'project-blah' and it's 3 environments 'feature-a', 'feature-b' and 'feature-c'. Do you wish to continue?

Lagoon CLI should then delete the environments first, and if they all succeed, then delete the project.

**Comment by tobybellwood** [comment]
Could this also include the logic to delete all environments, but then not delete the project (as is required on some clusters for billing purposes?)

**Comment by shreddedbacon** [comment]
It would be possible to add this logic to the CLI, but realistically the API should do it.

On deleting a project in the API, there should be an input option like the following. By default it will be false, and it will just remove all groups associated to the project except billing groups. But it will go ahead and delete the environments automagically.

```
mutation {
  deleteProject(input: {
    project: "my-project"
    forceDelete: "true"
  })
}
```

If true, then you know what would happen :boom:

**Comment by tobybellwood** [comment]
no - all environments need to be deleted before a project can be deleted as a safety measure.
