### ISSUE TITLE
Omitting --name flag in `list group-projects` command does not list all projects

### ISSUE THREAD

**Issue by nicksantamaria** [uselagoon/lagoon-cli#134]
**Describe the bug**

According to the inbuilt help text, omitting the `--name` flag from this command should list all project groups.

```
$ lagoon list group-projects --help | grep name
  -N, --name string   Name of the group to list users in (if not specified, will default to all groups)
```

However if this flag is omitted, no action is performed and the help text is displayed. 

**To Reproduce**

Run this command
```
lagoon list group-projects
```

**Expected behavior**
Expect to see a list of project groups.

**Comment by shreddedbacon** [comment]
This is very likely a copy-pasta error. Will look into the actual behaviour against the API and update accordingly.
