### ISSUE TITLE
Ability to send native graphQL queries

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-cli#141]
**Is your feature request related to a problem? Please describe.**

For advanced users, it would be nice to be able to send raw graphQL queries, e.g. for nested queries, that would never be part of 'core' Lagoon CLI.

**Describe the solution you'd like**

Perhaps a new command.

**Comment by shreddedbacon** [comment]
Do you think the output should just be the raw JSON response you would get from the API?

**Comment by seanhamlin** [comment]
Yeah, raw JSON is fine. These users are expected to be advanced, so they can pipe `jq` if needed etc.

**Comment by tobybellwood** [comment]
Adding to rewrite to-do list
