### ISSUE TITLE
Standardise the environment name format

### ISSUE THREAD

**Issue by Ahmedjabar** [uselagoon/lagoon-cli#147]
**Describe the bug**
The environment name is required in different formats for different commands. 

**To Reproduce**
1. Let us say we have `feature/abc` environment.
2. To SSH to the environment, you would use `lagoon ssh -p project-name -e feature-abc`
3. However, if you want to delete the environment, you will need to use `feature/abc`: 
`lagoon delete environment -p project-name -e feature/abc`. 
4. If you use `feature-abc`, you will get `Environment "feature-abc" does not exist` error.

**Expected behavior**
I would expect the same format to be used for all commands or at least the expected format should be documented.

**Comment by shreddedbacon** [comment]
This should be an easy fix. SSH is the only command where this is different, I think we just need to execute a get environment command to get the `openshiftProjectName` for the environment.

**Comment by AlexSkrypnyk** [comment]
@shreddedbacon 
this "inconsistency" been a huge pain for a day-to-day environment management. Any chance this can be prioritised please?

**Comment by AlexSkrypnyk** [comment]
in reality, seen how lagooncli is used by devs, it would be cool to support both normal and safe branch names for all commands, so devs would not have to guess which format it is.

**Comment by shreddedbacon** [comment]
Just merged #237 and will release soon, but it adds support for using the normal branch name as the environment name when using SSH commands. This brings it in line with other commands.

Unfortunately, the work to be able to support the "safe" branch name in other commands is not very easy, so the decision was made to just bring SSH in line.
