### ISSUE TITLE
Add new command for using rsync

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-cli#167]
**Is your feature request related to a problem? Please describe.**

It is quite hard to formulate the `rsync` string to copy a file from a PVC to and from your local.

**Describe the solution you'd like**

Lagoon CLI to generate the `rsync` command, just like it does for the `ssh` command

**Describe alternatives you've considered**

Manually formulating the string, but this took a long time, and I still failed at it.

**Additional context**

Known to work rsync command:

```bash
rsync -arvz \
 -e 'ssh -p 32222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=ERROR $NAMESPACE@ssh.lagoon.amazeeio.cloud service=$SERVICE container=$CONTAINER' \
 $SOURCE :$DESTFOLDER
```

**Comment by shreddedbacon** [comment]
This will come as part of this project which is still WIP https://github.com/amazeeio/lagoon-sync
