### ISSUE TITLE
Add support for backups

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-cli#170]
**Is your feature request related to a problem? Please describe.**
Allow to work with backups per environment:
- list
- restore
- download

**Describe the solution you'd like**
CLI to support a list of commands to list, restore and download backups. The specific commands are to be discussed within this issue.

**Describe alternatives you've considered**
CLI does not provide any alternatives. Direct querying GraphQL for this is not alternative in the context of CLI.

**Additional context**
From discussion with @shreddedbacon 
> But its a multi step approach. The first step is to list the backups and get the ID of the one you want. Then you need to trigger a restore using that backup id. this starts the process of retrieving it from s3. then you need to get the download url from the restored backup once its complete

**Comment by seanhamlin** [comment]
I have had another large customer request this in region.

**Comment by tnelson-doghouse** [comment]
Quick question: How close is this to being ready to go?  

Also, it'd be handy if that middle step were called "retrieve" instead of "restore" (so it'd be the same as the Web UI, and less confusing).  

Thanks!

**Comment by shreddedbacon** [comment]
> Quick question: How close is this to being ready to go?
> 
> Also, it'd be handy if that middle step were called "retrieve" instead of "restore" (so it'd be the same as the Web UI, and less confusing).
> 
> Thanks!

I've updated it to be `lagoon retrieve backup` as the command type to use now, this should make it less confusing hopefully. Let me know

I can probably release it soon, but you're also free to build it and try it out locally to see if it works for you, there is a dockerised builder so you don't need to install go, see the README in roof for build instructions

**Comment by tnelson-doghouse** [comment]
Regarding the new name, that's great; thanks very much :) .  

Good to know; I honestly doubt I'll get to it, but thanks for the info.

**Comment by AlexSkrypnyk** [comment]
@shreddedbacon 
Thank you so much for working on this!

Could you please create a release for this as it seems to be one of the most-wanted features from many clients.

Thanks

**Comment by shreddedbacon** [comment]
@AlexSkrypnyk will release soon, just have a few things to merge first
