### ISSUE TITLE
SSH Conn string does not restrict identity files to a specified file

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-cli#198]
**Describe the bug**
LagoonCLI uses a key specified with `-i` when connecting to an environment via SSH, bypassing the default key that may be loaded in the user's SSH agent, which results in using only the key specified with the `-i` option. All works as expected. Great.

When running the same command with `--conn-string`, the returned value does not limit the key to the specified one - the SSH will use any keys currently loaded in the users' SSH agent. This will be OK for majority of cases, but in case when default key is already used in Lagoon in another project, SSHing will fail with "no access" (because it is using the wrong key for the project the client is trying to connect to). 

Although the problem is on the client side, there is no consistency between how LagoonCLI handles SSH key internally with how it is printed in the connection string, which is assumed by the user to be the same.

A possible solution is to add `-o "IdentitiesOnly=yes"` to the printed connection string.

https://github.com/uselagoon/lagoon-cli/blob/643ede5f12f4ca6810da529a6ea3c6770893ea62/pkg/lagoon/ssh/main.go#L123

**To Reproduce**
1. Create a default SSH key and add it to project1
2. Create a custom SSH key and add it to project2
3. Run `lagoon -i /path/to/custom_key ssh -p project2 -e master` and assert that it is possible to connect
4. Run `lagoon -i /path/to/custom_key ssh -p project2 -e master --conn-string`
5. Copy the output SSH command and try to run
6. Access denied will be shown since the key from project 1 (default key) will be used.
7. Add `-V` to  SSH command and run again - you will see that the default key is offered first.

**Expected behavior**
Connection string to include all required SSH information that is identical to how LagoonCLI connects.

**Proposed solution**
Add `-o "IdentitiesOnly=yes"` to the printed connection string.

https://github.com/uselagoon/lagoon-cli/blob/643ede5f12f4ca6810da529a6ea3c6770893ea62/pkg/lagoon/ssh/main.go#L123

**Comment by shreddedbacon** [comment]
@AlexSkrypnyk we are open to PRs on the CLI if this solves your issue. I haven't had time to work on this, but if you have some time I'm more than happy to review a PR.

**Comment by seanhamlin** [comment]
If I understand the [SSH config page](https://linux.die.net/man/5/ssh_config) correctly and this [s.o post](https://superuser.com/questions/268776/how-do-i-configure-ssh-so-it-doesnt-try-all-the-identity-files-automatically), I think what should be done, if a private key is specified with the `-i` parameter in Lagoon-CLI, that we add 2 additional options to the SSH command:

```
ssh -o IdentitiesOnly=yes -i ~/.ssh/id_banana ...
```

This will prevent _all_ SSH keys being attempted, and instead use the key specified.
