### ISSUE TITLE
Homebrew - "Warning: Calling bottle :unneeded is deprecated! There is no replacement."

### ISSUE THREAD

**Issue by kmbremner** [uselagoon/lagoon-cli#208]
**Describe the bug**
Homebrew gives "Warning: Calling bottle :unneeded is deprecated! There is no replacement."

**To Reproduce**
1. Run `brew upgrade`

Error reports
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the amazeeio/lagoon-cli tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/amazeeio/homebrew-lagoon-cli/lagoon.rb:8
```

**Expected behavior**
Lagoon-cli should upgrade without error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Homebrew: 3.3.2-11-gef6d3dc
 - Homebrew/homebrew-core (git revision bd8c1a58207; last commit 2021-11-01)
 - Homebrew/homebrew-cask (git revision dd2a251425; last commit 2021-11-01)

**Comment by kmbremner** [comment]
This looks to be the offending line: https://github.com/uselagoon/lagoon-cli/blob/83b514b96a7f6e7c624f4bf153ff32fecfed557d/.github/tap-release.yml#L12

**Comment by christopher-hopper** [comment]
Came to report the same thing. I'm not sure if it is related but homebrew cannot upgrade lagoon either. 

It will always install version `0.11.4` even though that's outdated now. Current version reported as `0.11.6`.

**Comment by shreddedbacon** [comment]
Yea, our homebrew taps are broken at the moment because our automation tool we use is broken.

We're working on moving to a new tool, but I will see if I can get the tap updated manually.

**Comment by tobybellwood** [comment]
I'm looking at this rn actually :smile:

**Comment by tobybellwood** [comment]
fixed in https://github.com/uselagoon/lagoon-cli/releases/tag/v0.12.0

**Comment by bryangruneberg** [comment]
thanks @tobybellwood!
