### ISSUE TITLE
Add support for routerPattern attribute on project

### ISSUE THREAD

**Issue by nicksantamaria** [uselagoon/lagoon-cli#211]
**Is your feature request related to a problem? Please describe.**
Support was added for project-level `routerPattern` attributes in lagoon - see https://github.com/uselagoon/lagoon/pull/2806

At the moment this attribute is not available in lagoon-cli.

**Describe the solution you'd like**

*Part 1 - Support for modifying the attribute*
A new flag added to the add/update project commands.

```
lagoon update project \
  --project foo \
  --routerPattern '${environment}--${project}.lagoon.example.com'
```

*Part 2 - Support for viewing the attribute*
Seeing the current value in the `lagoon get project` output.

**Describe alternatives you've considered**
I haven't tried yet, but I assume this attribute should be available via the graphql api.

**Comment by tobybellwood** [comment]
yup - you can patch an existing project easily enough
```
mutation updateProject {
  updateProject(input:{
    id:1234
    patch:{
      routerPattern:"${service}-${environment}-${project}.lagoon.example.com"
    }
  }) {
    id
  }
}
```
But yup - we'll get support added to the cli too
