### ISSUE TITLE
SSH Portal support

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-cli#214]
**Is your feature request related to a problem? Please describe.**

SSH Portal support should be available in Lagoon soon. Lagoon CLI doesn't yet support it.

**Describe the solution you'd like**

I'd like to see support for the remote SSH Portal endpoints added to Lagoon CLI.

**Describe alternatives you've considered**

n/a

**Additional context**

This is just a tracking issue which depends on https://github.com/uselagoon/lagoon-charts/pull/382

**Comment by smlx** [comment]
I think a solution for this could be to assume that the ssh-portal endpoint has DNS along the lines of `ssh.<cluster base URL>` for all clusters.

That way the CLI would just have to query the cluster and get the SSH endpoint for it and/or generate it from the base URL.

**Comment by shreddedbacon** [comment]
Yeah, was thinking something like this too
