### ISSUE TITLE
Add support in the CLI for addition and removal of all notification types supported by Lagoon

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/lagoon-cli#225]
**Is your feature request related to a problem? Please describe.**

Lagoon currently supports five different notifications types, of which only two are supported by the CLI:
- Slack
- Rocket Chat

**Describe the solution you'd like**

The Lagoon CLI should also support the three other notification types:
- Microsoft Teams
- Email
- Webhook

**Describe alternatives you've considered**

N/A

**Additional context**

None

**Comment by vincenzodnp** [comment]
Would be nice to have it set before Nov 22, 2022 ;)
