### ISSUE TITLE
get project-metadata go struct error

### ISSUE THREAD

**Issue by GROwen** [uselagoon/lagoon-cli#266]
**Describe the bug**
The Lagoon CLI sub-command `project-metadata` throws the following error.

```
❯ lagoon get project-metadata -p project-name
Error: decoding response: json: cannot unmarshal object into Go struct field ProjectMetadata.Data.projectByName.metadata of type string
```

**To Reproduce**
1. In a terminal execute
`lagoon get project-metadata -p project-name`

**Expected behavior**
The projects metadata property is returned.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: n/a
 - Version: 12
 - Lagoon CLI version:
 ```
❯ lagoon version
lagoon v0.17.0 (go-1.16)
built 2023-02-03T00:42:39Z
```

**Additional context**
The same error is returned for the `lagoon list projects-by-metadata` sub-command.

**Comment by shreddedbacon** [comment]
Ah, I know this one. Will try get a quick fix out
