### ISSUE TITLE
A command returning non-zero exit executed via `lagoon ssh -C` breaks terminal output

### ISSUE THREAD

**Issue by Leksat** [uselagoon/lagoon-cli#269]
**Describe the bug**

If I run `lagoon ssh -C` with a command that errors, my terminal goes crazy 😅 

<img width="415" alt="Screenshot_2023-03-30_at_19_14_01" src="https://user-images.githubusercontent.com/989015/228900319-09eb083c-6ee1-45a4-86bf-4098e22c4507.png">

(Also, there is no output from the command)

<details>
  <summary>Text version</summary>
  
  ```
ambp% lagoon ssh -p project -e dev -C 'some-error-command'
Process exited with status 127
                              %
ambp% echo "notice this\nline 2\n line 3"
notice this
           line 2
                  line 3
                        %
ambp% echo "how \n it \n does \n it ? 😂"
how
     it
         does
               it ? 😂
                      %
ambp% echo "how to undo it?"
how to undo it?
               %
ambp%
  ```
</details>

**STR**

1. `lagoon ssh -p MY-PROJECT -e MY-ENV -C 'some-error-command'`
2. Try to run some other command that outputs something

It looks especially nice if you run something that rewrites the output dynamically. For example, `npm i`

**Expected behavior**

My terminal stays sane 😁

**Additional context**

Environment: latest macos, `zsh` without profile loaded (`zsh --no-rcs`)

```
ambp% lagoon --version
lagoon v0.17.0 (go-1.16)
                        built 2023-02-03T00:42:39Z
                                                  %
```

**Comment by shreddedbacon** [comment]
Thanks, I just put up a PR that handles errors differently that should help prevent this from happening.

**Comment by Leksat** [comment]
Thanks for the super quick fix! Is there a chance for a release?

**Comment by shreddedbacon** [comment]
Just need to verify some other merges and then will aim for a release tomorrow/day after

**Comment by Leksat** [comment]
Upgraded, tested, works! Thank you 🤍

**Comment by shreddedbacon** [comment]
Thanks for letting me know, glad it helps you out :)
