### ISSUE TITLE
List groups for a specific user

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-cli#271]
**Is your feature request related to a problem? Please describe.**

At present, it is possible to list users in a specific group, but not the opposite, to list all the groups (and roles within) a specific user is in. This is useful for instance to debug the access a particular user has.

**Describe the solution you'd like**

```
lagoon list groups -E me@example.com
```

**Describe alternatives you've considered**

```
lagoon list users | grep me@example.com
```

However this query takes ages to return, so I suspect it is non-optimal to run.

**Additional context**

This will help remove the need to log into Keycloak for debugging of access control.

**Comment by PeterSalsa** [comment]
Alternatively, a solution might be:

`lagoon get user -E me@example.com`

Which would then list info about the user, including the groups and projects they've been added to. Kind of like this page in GitLab (https://projects.govcms.gov.au/admin/users/sean.hamlin/projects):

![image](https://user-images.githubusercontent.com/126627037/229938967-3b89da4d-2a5a-41ee-a44f-d71852140279.png)

**Comment by shreddedbacon** [comment]
Just have to consider that all of these queries would only be able to be used by admins, since normal users cannot query other users.

**Comment by shreddedbacon** [comment]
>However this query takes ages to return, so I suspect it is non-optimal to run.

This won't be a problem in lagoon version 2.14.+ as there are numerous API optimisations that make these queries faster to perform
