### ISSUE TITLE
Show `deploymentsDisabled` in `get project`

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-cli#291]
**Is your feature request related to a problem? Please describe.**

It would be ace if the flag `deploymentsDisabled` could be exposed in `lagoon get project -p PROJECTNAME`

**Describe the solution you'd like**

A new key emitted `deploymentsDisabled` with the same value as what is in the DB, `0` or `1`.

**Comment by shreddedbacon** [comment]
I'd opt for actually returning it as a boolean representation than a `0|1`, as boolean is more obvious at a glance
