### ISSUE TITLE
Valid command producing an error shows usage string unnecessarily when using "list variables"

### ISSUE THREAD

**Issue by wolcen** [uselagoon/lagoon-cli#296]
**Describe the bug**
Listing variables that results in an error, also displays the `Usage` text unnecessarily. This occurs for me when an environment does not have any variables as yet.

**To Reproduce**
1. Run `lagoon list variables -p yourenv` for an environment having no existing variables.

**Expected behavior**
The error is correct; The display of command usage is unnecessary/potentially confusing.

**Screenshots**
```shell
$ lagoon list variables -p example-com
Error: There are no variables for project 'example-com'
Usage:
  lagoon list variables [flags]

Aliases:
  variables, v
...
```

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by tobybellwood** [comment]
Closed in #298
