### ISSUE TITLE
Reports feature

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-cli#32]
**Description**

It would be great to be able to bake in certain pre-canned reports into the CLI and just dump out the results there (e.g. in a CLI table).

**Describe the solution you'd like**

e.g. 

* Top HTTP 404s in the last 24 hours
* Top IPs in the last 24 hours

etc.

**Describe alternatives you've considered**

**Additional context**

This will enable the logs backend to be more flexible on implementation. It also will prevent people from having to learn Elastic Search syntax.

**Comment by tobybellwood** [comment]
These are best in the UI?
