### ISSUE TITLE
`add user-group` doesn't error on invalid role

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon-cli#336]
**Describe the bug**
When adding a user to a group, if the role is misspelled there will be no errors and the user will be added as guest.

**To Reproduce**
1. Add a user to a group with a role that is not one of the allowed values. The result is `success`. Notice the misspelled `MANTAINER`:
    ```
    ➜  ~ lagoon add user-group -E user@example.com -N project-drupal-example -R MANTAINER
    Result: success
    ```

2. View the members of the group, notice that the user has been added as `GUEST`:
    ```
    ➜  ~ lagoon list group-users -N project-drupal-example                                         
    ID                                  	GROUPNAME               	EMAIL                        	ROLE
    e6217ee9-c591-44dd-9b4d-5ebedfafb60c	project-drupal-example	default-user@drupal-example	MAINTAINER
    e6217ee9-c591-44dd-9b4d-5ebedfafb60c	project-drupal-example	user@example.com   	GUEST
    ```

**Expected behavior**
If I don't provide a valid role, I should get an error so that I don't grant users an incorrect role.

**Additional context**
Running the command with `--debug` shows the graphql request is passing the `GUEST` role, so it's not a fallback in the Lagoon api.

**Comment by shreddedbacon** [comment]
The fallback to `GUEST` is if the `--role` flag is omitted. This should be a relatively easy fix to check if the flag is provided to pass whatever is in it, rather than try and be smart about it.
