### ISSUE TITLE
Lagoon cli delete Team notification from project doesn't work

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon-cli#340]
**Describe the bug**
With Lagoon cli is not possible to remove a Microsoft Team notification from a project.
The usual syntax would have been `lagoon delete n pm -p <project> -n <notification_name>` but the method doesn't take into accoun the notification name.

The error is ```Error: unknown shorthand flag: 'n' in -n```

**To Reproduce**
1. run `lagoon delete n pm -p <project> -n <notification_name>` 
2. See error `Error: unknown shorthand flag: 'n' in -n`

**Expected behavior**
Notification being removed from the project

**Additional context**
lagoon v0.20.2 (go-1.16)
built 2023-12-06T23:01:32Z

**Comment by shreddedbacon** [comment]
This might be a bug in the alias for the command as you're using `pm` but the command [has an incorrect `pr`](https://github.com/uselagoon/lagoon-cli/blob/v0.21.1/cmd/notificationsteams.go#L250) . 

Try use the full command path for now 
```
lagoon delete notification project-microsoftteams --project $project --name $name
```
