### ISSUE TITLE
Missing linefeed in error message

### ISSUE THREAD

**Issue by tnelson-doghouse** [uselagoon/lagoon-cli#365]
**Describe the bug**
There's no line feed (\n) at the end of the error message, so the next line runs onto it.  

**To Reproduce**

```
$ lagoon list variables --project <project> -e <environment>
There are no variables for environment 'deploy/lagoon/pre-production' in project 'district-captivate'ID PROJECT ENVIRONMENT     SCOPE       NAME
```
Note how in the above output, the error and the column headings are all on the same line (in github, you may need to scroll to see this).  

**Expected behavior**
There is a carriage return after the error message (not sure the column headings need to be there either, but whatever)

**Desktop (please complete the following information):**
 - OS: Fedora 36 running in WSL
 - Browser: N/A
 - Version v0.21.3

**Additional context**

**Comment by shreddedbacon** [comment]
This will be fixed in the next CLI release which will be soon. We are preparing some release notes ahead of its release as it will be a big one

**Comment by tnelson-doghouse** [comment]
Great!

**Comment by CGoodwin90** [comment]
Resolved in https://github.com/uselagoon/lagoon-cli/releases/tag/v0.30.0
