### ISSUE TITLE
unify notifications list, add email and teams

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon-cli#88]
**Is your feature request related to a problem? Please describe.**
Currently I need to run two commands to see all the rocketchat and/or slack notifications associated with a project. With the addition of Microsoft Teams and email notifications, this would then require me running _4_ commands to see all the notifications.

**Describe the solution you'd like**
I should be able to run a simple command like `lagoon list notifications -p project-name` and get a list of all the notifications of a project, regardless of type.

**Comment by tobybellwood** [comment]
This has now been implemented!
