### ISSUE TITLE
allow adding of Teams and email notifications

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon-cli#89]
Lagoon now supports notifications to Microsoft Teams and email, these should be present as options in lagoon-cli.

**Comment by shreddedbacon** [comment]
CLI now supports versioning in requests, we can use this feature to ensure that only supported Lagoons can be targeted. 

Need to have commands for
* Adding notifications
* Deleting notification
* Adding notification to project
* Removing notification from project
* Listing notifications on a project

**Comment by tobybellwood** [comment]
This has now been implemented
