### ISSUE TITLE
Integration with oh-my-zsh plugins

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-cli#90]
**Is your feature request related to a problem? Please describe.**

I would love to know which lagoon I am currently logged into in my PS1. Basically this value:

```bash
cat ~/.lagoon.yml | shyaml get-value current
```

I wonder if a `oh-my-zsh` plugin could be published.

**Comment by shreddedbacon** [comment]
#92 would give a command `lagoon config current` that you could use in your PS1.

Not familiar with `oh-my-zsh` though, will need to research

**Comment by tobybellwood** [comment]
I don't think we would make this plugin, but if someone wanted to, or could document how they did their  PS1, they could :wink:
